CREATE TABLE Pay_Request(
  SysNo INT PRIMARY KEY IDENTITY(1,1),
  OrderId NVARCHAR(256),
  PaymentAmt DECIMAL(19,2) NOT NULL,
  PayType INT NOT NULL,
  NotifyUrl NVARCHAR(1024),
  ReturnUrl NVARCHAR(1024),
  RequestData NVARCHAR(MAX),
  ExecuteResult INT DEFAULT 0 NOT NULL,
  ResultDesc NVARCHAR(1024),
  RequestSystemId INT DEFAULT 0 NOT NULL,
  Status INT DEFAULT 0 NOT NULL,
  CreateTime DATETIME DEFAULT GETDATE() NOT NULL
);
CREATE INDEX IX_Pay_Request_OrderId_PayType ON Pay_Request(OrderId,PayType);

CREATE TABLE Pay_Result(
  SysNo INT PRIMARY KEY IDENTITY(1,1),
  RequestSysNo INT DEFAULT 0 NOT NULL,
  OrderId NVARCHAR(256),
  TradeNo NVARCHAR(256),
  PaymentAmt DECIMAL(19,2) NOT NULL,
  PayType INT NOT NULL,
  RequestData NVARCHAR(MAX),
  ExecuteResult INT DEFAULT 0 NOT NULL,
  ResultDesc NVARCHAR(1024),
  NotifyStatus INT DEFAULT 0 NOT NULL,
  CreateTime DATETIME DEFAULT GETDATE() NOT NULL
);

CREATE TABLE Pay_NotifyBack(
  SysNo INT PRIMARY KEY IDENTITY(1,1),
  ResultSysNo INT DEFAULT 0 NOT NULL,
  Msg NVARCHAR(1024),
  Status INT DEFAULT 0 NOT NULL,
  CreateTime DATETIME DEFAULT GETDATE() NOT NULL
);

CREATE TABLE Pay_Refund(
  SysNo INT PRIMARY KEY IDENTITY(1,1),
  OrderId NVARCHAR(256),
  TradeNo NVARCHAR(256),
  PaymentAmt DECIMAL(19,2) NOT NULL,
  RefundOrderId NVARCHAR(256),
  RefundAmt DECIMAL(19,2) NOT NULL,
  RefundNo NVARCHAR(256),
  PayType INT NOT NULL,
  RequestData NVARCHAR(MAX),
  ExecuteResult INT DEFAULT 0 NOT NULL,
  ResultDesc NVARCHAR(1024),
  RequestSystemId INT DEFAULT 0 NOT NULL,
  CreateTime DATETIME DEFAULT GETDATE() NOT NULL
);